### ISSUE TITLE
Header/Footer of docx file

### ISSUE THREAD

**Issue by Gebes** [bobiverse/docxplate#16]
Hello! Thanks for the excellent work!

Is it just me, or is text in the header/footer not being replaced?

**Comment by bobiverse** [comment]
Looks like this issue was predicted:
```go
	f := t.documentMain // TODO: loop all xml files
```
so i will try to fix/test it :+1:

**Comment by Gebes** [comment]
Thank you for looking into it! That is awesome.
So far, this is the best Word Processing Lib I could find on the web, and your solution to rendering out lists is excellent and clever!

**Comment by bobiverse** [comment]
Thank you! Please check the new version when possible. It seems a bit of motivation was all I needed to complete this feature. :)

**Comment by Gebes** [comment]
Wow, that was quick! Thanks! Now it is working perfectly for both header and footer
