### ISSUE TITLE
new bug after https://github.com/bobiverse/docxplate/pull/18

### ISSUE THREAD

**Issue by bobiverse** [bobiverse/docxplate#19]
@nightmorning one more bug emerged after https://github.com/bobiverse/docxplate/pull/18

```bash
go test
```
```
--- FAIL: TestPlaceholders (0.00s)
panic: runtime error: slice bounds out of range [20:2] [recovered]
	panic: runtime error: slice bounds out of range [20:2]

```

**Comment by bobiverse** [comment]
I was quick to approve your PR, but why did you want to match `{A}}` and `{{B}` ?

**Comment by bobiverse** [comment]
Ok this is deeper problem and added some time ago. I'll check in near future :)

**Comment by nightmorning** [comment]
I'm just trying to fix this issue, it seems like there are still some issues that haven't been considered yet

**Comment by nightmorning** [comment]
> @nightmorning one more bug emerged after #18
> 
> ```shell
> go test
> ```
> 
> ```
> --- FAIL: TestPlaceholders (0.00s)
> panic: runtime error: slice bounds out of range [20:2] [recovered]
> 	panic: runtime error: slice bounds out of range [20:2]
> ```

There will be errors when using {{A} in my template

**Comment by nightmorning** [comment]
The result I want is not to replace the placeholders, so that users can discover errors on their own

**Comment by bobiverse** [comment]
I think we will move to remove this quick-fix at all. And thanks for fixing bugs you ecountered :)

**Comment by nightmorning** [comment]
thanks👍🏻
