### ISSUE TITLE
Can line break symbols be supported?  just like '\n' 

### ISSUE THREAD

**Issue by xinyidev** [bobiverse/docxplate#26]

**Comment by sanq477** [comment]
Hi, @bobiverse  For example, I need to implement multiple lines in a table cell. Currently, when a multiple-line list is displayed in a cell, it generates multiple lines instead of generating a list in the cell. Can the effect of line break be achieved by recognizing '\n'?

**Comment by bobiverse** [comment]
Good news @sanq477 ! Got working example with new lines. See `t.docx_test.go` 

 ```go
func TestDepthStructToParams(t *testing.T) {
	var user = User{
		Name:  "Alice",
		Age:   27,
		Motto: "Always stay humble.",
		Friends: []*User{
			{Name: "Bob", Age: 28, Motto: "Be\nbrave,\nbe\nbold.", Friends: []*User{
				{Name: "Cecilia", Age: 29, Motto: "Chase\nyour\ndreams."},
```
![image](https://github.com/bobiverse/docxplate/assets/18720548/daa1ebd2-9fa7-4e2c-b896-6ea58bd60038)

with example `"Chase\nyour\ndreams."` will produce:
![image](https://github.com/bobiverse/docxplate/assets/18720548/36084651-6bfe-4c2c-aef3-c6da69f97f46)
