### ISSUE TITLE
👋 whether there are plans to add conditional branches (if syntax) to the template

### ISSUE THREAD

**Issue by JairoGuo** [bobiverse/docxplate#28]

**Comment by bobiverse** [comment]
Hi!

Currently, there are no plans to avoid bloat in the document and to keep most of the logic external. I agree that for block structures (such as tables and images), it might sometimes be necessary, but there are no immediate plans for this.

For my personal use, I create a separate document for each specific case. This approach helps keep my documents organized, and I always know which one to edit if there are errors.
