### ISSUE TITLE
打印速度特别慢

### ISSUE THREAD

**Issue by wr6412305** [bobiverse/docxplate#30]
tdoc.Params()绑定属性特别慢
2024-06-12 14:32:09 c1.2
154 c1.3
//进行tdoc.Params(changeReport)
2024-06-12 14:32:21 c2
2024-06-12 14:32:21 c3
154条列表循环,花了11秒

**Comment by bobiverse** [comment]
¡Gracias! Lo investigaré. Quizás haya una manera rápida de mejorar la velocidad.

**Comment by bobiverse** [comment]
Näyttää siltä, että uusin versio voisi parantaa suorituskykyä. Tarkista siis uudelleen, onko hitaus edelleen olemassa.
