### ISSUE TITLE
Add "upper" "lower" "capitalize" "title" tags

### ISSUE THREAD

**Issue by 8thgencore** [bobiverse/docxplate#35]
Good afternoon. 
It would be nice to see the "**upper**" "**lower**" "**capitalize**" "**title**" tags for formatting the text output. For example, instead of `{{name:upper}}`, the name `jhon` will be substituted as `JHON`

**Comment by bobiverse** [comment]
Hi! I'm generally against any _single data point_ manipulation that can be done before sending it to `docxplate`.

For example:
- :no_entry_sign: string **lowercase**, **uppercase**  transformations etc. - These should be done beforehand.
- :no_entry_sign: number: **add**, **substraction**, etc. - These should be done beforehand.
- :green_circle: **text color** - This cannot be done beforehand, as _docx_ uses `xml` styling.

---
There was a similar proposal for an `if..then..else` construction, which is more likely to be implemented. Currently, to achieve this, you need two templates with the same structure. Before sending it to `docxplate`, there is Golang code with `if..else`.

**Comment by 8thgencore** [comment]
You probably haven't come across a situation where a field in a document should be like John in different places, and JOHN somewhere.
I think there will be very good triggers `:lower` `:upper` `:title` `:capitalize`. 
I am ready to write the code myself and upload it to the pull request.

**Comment by bobiverse** [comment]
Yeah, i have no problem to merge this feature when it's ready :+1: 

If you can, try to relate to trigger scopes https://github.com/bobiverse/docxplate/blob/419186ae60f0f847c9dfe94ec180f11b95c021b9/ParamTrigger.go#L24
so it can transform not only placeholder value, but also scope `:row`, `:cell` it would add some extra depth to this feature. :bow:

**Comment by bobiverse** [comment]
Release: `v1.4.0`
